version: '2'
services:
  app:
    build: .
    image: flask-task:test
    command: /bin/bash
    env_file:
      - env/develop
    ports:
      - $FLASK_APP_HOST_PORT:5000
    working_dir: /app/src
    volumes:
      - ./src:/app/src
      - ./htmlcov:/app/src/htmlcov