version: '2'
services:
  app:
    build: .
    image: flask-task:test
    command: /bin/bash
    environment:
      - FLASK_APP_PORT=8080
    ports:
      - 8080:8080
    working_dir: /app/src
    volumes:
      - ./src:/app/src